name: 自动检测更新并部署 Hexo

on:
  push:
    branches:
      - main # 监控 main 分支的更新
  workflow_dispatch: # 手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 安装 Hexo CLI
        run: npm install hexo-cli -g

      - name: 初始化 Hexo 博客
        run: |
          if [ ! -d "blog" ]; then
            hexo init blog
          fi
          cd blog
          npm install
          npm install hexo-deployer-git --save

      - name: 部署 Hexo 博客
        run: |
          cd blog
          hexo clean
          hexo generate
          hexo deploy
